# Copyright 2026 StateKnot contributors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "stateknot-store-postgres"
description = "PostgreSQL durability provider for StateKnot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/stateknot-store-postgres"
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx-core.workspace = true
sqlx-postgres.workspace = true
stateknot-core = { version = "=0.0.0", path = "../stateknot-core" }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
